### ISSUE TITLE
keel & kraken

### ISSUE THREAD

**Issue by barokoko** [cferdinandi/keel#29]
For less experienced git & gulp users like me: what is the recommended way to start a new project with keel, kraken and astro?

**Comment by cferdinandi** [comment]
Hi there! So, you have a few different options, which kind of makes things a bit more difficult because you have to choose which one works for you. You need to decide if you want to:

1. Use Sass and JS modules with Gulp.
2. Use Sass and JS modules with another build system (command line like Grunt, or GUI like [CodeKit or Prepos](http://cferdinandi.github.io/kraken/working-with-the-source-files.html#gui-source-compilers)).
3. Use pre-compiled CSS and JS.

**Option 1**

We're going to use Keel as our main project, and copy-paste the required stuff from the other projects into it.

1. Download Keel, Kraken, and Astro from GitHub as zip files using the download link/button.
2. Unzip them.
3. Copy the contents of the `src` > `sass` > `components` directory in Kraken into the same directory in Keel.
4. Open up `main.scss` in Kraken, and copy-paste it's contents into the same file in Keel, leaving the existing content in tact.
5. In Astro, copy-paste the `src` > `js` files into the `src` > `js` > `main` directory in Keel. 
6. In Astro, copy-paste the `src` > `sass` > `components` files into the same directory in Keel. Again, add the appropriate reference in Keel's `main.scss` files.
7. Follow the instructions in Keel's documentation to run your Gulp build and start styling your theme. You'll obviously need to refer to Kraken's docs for the appropriate CSS, markup structure, etc.

**Option 2**

1. Follow steps 1-6 from Option 1.
2. Configure your GUI to use the `src` directory in Keel, or restructure your files to match the GUI's required setup (this will vary wildly depending on which piece of compiling software you're using).
3. Run your GUI or build tool as instructed.

**Option 3**

1. Copy the contents of Keel's `dist` > `css` > `main.css` file into Kraken's `dist` > `css` > `main.css` file. I'd recommend directly above the `/** @section Overrides */` content.
2. Copy your now updated `main.css` file in Kraken into Keel's `dist` > `css` directory, overriding the file there.
3. Copy-paste the contents from Astro's `dist` > `css` > `astro-*.css` file or files (pick your version) into the updated `main.css` file in Keel. I'd again recommend just before the Overrides stuff.
4. Copy-paste the contents of the `dist` > `js` > 'classList.js' and `astro.js` files into Keel's `dist` > `js` > `main.js` file.
5. Modify your CSS as desired, and add styles to your theme files, etc. etc.

Hope that helps!

**Comment by barokoko** [comment]
OK.  I used Option 1 and 2 and wondered, if I´m just not clever enough to do it a better way, particularly handling of updates. Real reason of my question was lazyness. Thanks for your answer.

**Comment by cferdinandi** [comment]
I'm certain using a [package manager](https://github.com/cferdinandi/astro#installing-with-package-managers) would be faster, but I've yet to dig into that myself.
